.TH "ho_array" 3 "22 Jul 2008" "Version 0.10.13" "libhocr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ho_array \- libhocr array struct  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ho_array.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "double * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
libhocr array struct 
.SH "Field Documentation"
.PP 
.SS "int \fBho_array::height\fP"
.PP
.SS "int \fBho_array::width\fP"
.PP
.SS "double* \fBho_array::data\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libhocr from the source code.
