.TH "ho_bitmap" 3 "12 Feb 2008" "Version 0.10.5" "libhocr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ho_bitmap \- libhocr bitmap struct  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ho_bitmap.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBtype\fP"
.br
.ti -1c
.RI "int \fBfont_height\fP"
.br
.ti -1c
.RI "int \fBfont_width\fP"
.br
.ti -1c
.RI "int \fBfont_spacing\fP"
.br
.ti -1c
.RI "int \fBline_spacing\fP"
.br
.ti -1c
.RI "int \fBavg_line_fill\fP"
.br
.ti -1c
.RI "int \fBcom_line_fill\fP"
.br
.ti -1c
.RI "unsigned char \fBnikud\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBrowstride\fP"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
libhocr bitmap struct 
.SH "Field Documentation"
.PP 
.SS "unsigned char \fBho_bitmap::type\fP"
.PP
.SS "int \fBho_bitmap::font_height\fP"
.PP
.SS "int \fBho_bitmap::font_width\fP"
.PP
.SS "int \fBho_bitmap::font_spacing\fP"
.PP
.SS "int \fBho_bitmap::line_spacing\fP"
.PP
.SS "int \fBho_bitmap::avg_line_fill\fP"
.PP
.SS "int \fBho_bitmap::com_line_fill\fP"
.PP
.SS "unsigned char \fBho_bitmap::nikud\fP"
.PP
.SS "int \fBho_bitmap::x\fP"
.PP
.SS "int \fBho_bitmap::y\fP"
.PP
.SS "int \fBho_bitmap::height\fP"
.PP
.SS "int \fBho_bitmap::width\fP"
.PP
.SS "int \fBho_bitmap::rowstride\fP"
.PP
.SS "unsigned char* \fBho_bitmap::data\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libhocr from the source code.
