.TH "ho_objlist" 3 "3 Jun 2008" "Version 0.10.10" "libhocr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ho_objlist \- libhocr object list struct  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ho_objmap.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBallocated_size\fP"
.br
.ti -1c
.RI "\fBho_obj\fP * \fBobjects\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
libhocr object list struct 
.SH "Field Documentation"
.PP 
.SS "int \fBho_objlist::size\fP"
.PP
.SS "int \fBho_objlist::allocated_size\fP"
.PP
.SS "\fBho_obj\fP* \fBho_objlist::objects\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libhocr from the source code.
