.TH "ho_objmap" 3 "27 Jun 2008" "Version 0.10.11" "libhocr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ho_objmap \- libhocr object map struct  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ho_objmap.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int * \fBmap\fP"
.br
.ti -1c
.RI "\fBho_objlist\fP * \fBobj_list\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
libhocr object map struct 
.SH "Field Documentation"
.PP 
.SS "int \fBho_objmap::x\fP"
.PP
.SS "int \fBho_objmap::y\fP"
.PP
.SS "int \fBho_objmap::height\fP"
.PP
.SS "int \fBho_objmap::width\fP"
.PP
.SS "int* \fBho_objmap::map\fP"
.PP
.SS "\fBho_objlist\fP* \fBho_objmap::obj_list\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libhocr from the source code.
