.TH "ho_obj" 3 "10 Feb 2008" "Version 0.10.5" "libhocr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ho_obj \- libhocr object struct  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ho_objmap.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "int \fBreading_index\fP"
.br
.ti -1c
.RI "double \fBweight\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
libhocr object struct 
.SH "Field Documentation"
.PP 
.SS "int \fBho_obj::index\fP"
.PP
.SS "int \fBho_obj::reading_index\fP"
.PP
.SS "double \fBho_obj::weight\fP"
.PP
.SS "int \fBho_obj::x\fP"
.PP
.SS "int \fBho_obj::y\fP"
.PP
.SS "int \fBho_obj::width\fP"
.PP
.SS "int \fBho_obj::height\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libhocr from the source code.
