.TH "ho_pixbuf" 3 "1 Feb 2008" "Version 0.10.5" "libhocr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ho_pixbuf \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ho_pixbuf.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBn_channels\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBrowstride\fP"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char \fBho_pixbuf::n_channels\fP"
.PP
.SS "int \fBho_pixbuf::height\fP"
.PP
.SS "int \fBho_pixbuf::width\fP"
.PP
.SS "int \fBho_pixbuf::rowstride\fP"
.PP
.SS "unsigned char* \fBho_pixbuf::data\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libhocr from the source code.
