src/ho_string.h
NAME
src/ho_string.h - libhocr C language header.
SYNOPSIS
Data Structures
struct ho_string
libhocr string struct
Defines
#define HO_STRING_H 1
Functions
ho_string * ho_string_new ()
creats a new ho_string struct
int ho_string_free (ho_string *s_str)
free a hocr_text_buffer struct from memory
int ho_string_cat (ho_string *s_str, const char *text)
add a string to hocr_text_buffer struct
int ho_string_set (ho_string *s_str, const char *text)
set a string to ho_string struct
char * ho_string_get (const ho_string *s_str)
get the string of ho_string struct
ho_string * ho_string_copy (const ho_string *s_str)
copy ho_string struct
Detailed Description
libhocr C language header.
libhocr - LIBrary for Hebrew Optical Character Recognition
Define Documentation
#define HO_STRING_H 1
Function Documentation
ho_string* ho_string_new ()
creats a new ho_string struct
Returns:
pointer to a newly allocate ho_string or null.
Referenced by hocr::Hocr::do_font_recognition().
int ho_string_free (ho_string * s_str)
free a hocr_text_buffer struct from memory
Parameters:
s_str pointer to ho_string struct.
Returns:
1
Referenced by hocr::Hocr::do_font_recognition(), hocr::Hocr::set_bitmap(), hocr::Hocr::set_pixbuf(), and hocr::Hocr::~Hocr().
int ho_string_cat (ho_string * s_str, const char * text)
add a string to hocr_text_buffer struct
Parameters:
s_str pointer to hocr_text_buffer struct.
text pointer to the string to be added to the buffer.
Returns:
new size of text
int ho_string_set (ho_string * s_str, const char * text)
set a string to ho_string struct
Parameters:
s_str pointer to hocr_text_buffer struct.
text pointer to the string to be set to the buffer.
Returns:
new size of text
char* ho_string_get (const ho_string * s_str)
get the string of ho_string struct
Parameters:
s_str pointer to hocr_text_buffer struct.
Returns:
pointer to a newly allocated string (use free to free it)
ho_string* ho_string_copy (const ho_string * s_str)
copy ho_string struct
Parameters:
s_str pointer to hocr_text_buffer struct.
Returns:
new ho_string
Author
Generated automatically by Doxygen for libhocr from the source code.