.TH "hocr" 3 "3 Jun 2008" "Version 0.10.10" "libhocr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hocr \- the libhocr namespace.  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBHocr\fP"
.br
.RI "\fI\fBHocr\fP class. \fP"
.in -1c
.SH "Detailed Description"
.PP 
the libhocr namespace. 

namespace for Hebrew Optical Character Recognition 
.SH "Author"
.PP 
Generated automatically by Doxygen for libhocr from the source code.
