hocr::Hocr
NAME
hocr::Hocr - Hocr class.
SYNOPSIS
#include <hocrpp.h>
Public Member Functions
Hocr (ho_pixbuf *m_in=NULL)
Hocr constructor.
~Hocr ()
Hocr destructor.
int set_pixbuf (ho_pixbuf *m_in)
set pixbuf
int set_bitmap (ho_bitmap *m_in)
set b/w bitmap
ho_pixbuf * get_pixbuf ()
get pixbuf
ho_bitmap * get_bitmap ()
get bitmap
int save_bitmap_as_pnm (const char *filename)
save bitmap as pnm
int save_bitmap_as_tiff (const char *filename)
save bitmap as tiff (neads a tiff enabled libhocr)
ho_pixbuf * get_bitmap_pixbuf ()
get bitmap pixbuf
ho_pixbuf * get_layout_pixbuf ()
get layout pixbuf
const char * get_text ()
get text
int get_progress ()
get progress of ocr
int do_image_processing ()
do image processing
int do_layout_analysis ()
do layout analysis
int do_font_recognition ()
do font recognition
int do_ocr ()
do ocr
int get_html ()
get html param
int set_html (const unsigned char html_in)
set html param
int get_font ()
get font param
int set_font (const int font_in)
set font param
unsigned char get_nikud ()
get nikud param
unsigned char set_nikud (const unsigned char nikud_in)
set nikud param
int get_paragraph_setup ()
get paragraph setup param
int set_paragraph_setup (const int paragraph_setup_in)
set paragraph setup param
const char * get_build_string ()
get build string
Data Fields
int progress
Detailed Description
Hocr class.
class for Hebrew Optical Character Recognition
Constructor & Destructor Documentation
hocr::Hocr::Hocr (ho_pixbuf * m_in = NULL) [inline]
Hocr constructor.
References progress.
hocr::Hocr::~Hocr () [inline]
Hocr destructor.
References ho_bitmap_free(), ho_layout_free(), ho_pixbuf_free(), and ho_string_free().
Member Function Documentation
int hocr::Hocr::set_pixbuf (ho_pixbuf * m_in) [inline]
set pixbuf
Parameters:
m_in the pixbuf to use
Returns:
0
References ho_bitmap_free(), ho_layout_free(), ho_pixbuf_free(), ho_string_free(), and progress.
int hocr::Hocr::set_bitmap (ho_bitmap * m_in) [inline]
set b/w bitmap
Parameters:
m_in the b/w bitmap to use
Returns:
0
References ho_bitmap_free(), ho_layout_free(), ho_pixbuf_free(), ho_string_free(), and progress.
ho_pixbuf* hocr::Hocr::get_pixbuf () [inline]
get pixbuf
Returns:
the object pixbuf
ho_bitmap* hocr::Hocr::get_bitmap () [inline]
get bitmap
Returns:
the object bitmap
int hocr::Hocr::save_bitmap_as_pnm (const char * filename) [inline]
save bitmap as pnm
Parameters:
filename the the image file name
Returns:
the object bitmap
References ho_bitmap_pnm_save().
int hocr::Hocr::save_bitmap_as_tiff (const char * filename) [inline]
save bitmap as tiff (neads a tiff enabled libhocr)
Parameters:
filename the the image file name
Returns:
the object bitmap
References ho_bitmap_tiff_save().
ho_pixbuf* hocr::Hocr::get_bitmap_pixbuf () [inline]
get bitmap pixbuf
Returns:
a pixbuf of the object bitmap
References ho_pixbuf_free(), ho_pixbuf_new_from_bitmap(), and ho_pixbuf_to_rgb().
ho_pixbuf* hocr::Hocr::get_layout_pixbuf () [inline]
get layout pixbuf
Returns:
a pixbuf of the object layout
References ho_pixbuf_new_from_layout().
const char* hocr::Hocr::get_text () [inline]
get text
Returns:
the recognized text
References ho_string::string.
int hocr::Hocr::get_progress () [inline]
get progress of ocr
Returns:
the progress 0..100
References progress.
int hocr::Hocr::do_image_processing () [inline]
do image processing
Returns:
0
References ho_bitmap_free(), hocr_image_processing(), and progress.
Referenced by do_ocr().
int hocr::Hocr::do_layout_analysis () [inline]
do layout analysis
Returns:
0
References ho_layout_free(), hocr_layout_analysis(), and progress.
Referenced by do_ocr().
int hocr::Hocr::do_font_recognition () [inline]
do font recognition
Returns:
0
References ho_string_free(), ho_string_new(), hocr_font_recognition(), and progress.
Referenced by do_ocr().
int hocr::Hocr::do_ocr () [inline]
do ocr
Returns:
0
References do_font_recognition(), do_image_processing(), and do_layout_analysis().
int hocr::Hocr::get_html () [inline]
get html param
Returns:
FALSE-no html in output, TRUE-output html text
int hocr::Hocr::set_html (const unsigned char html_in) [inline]
set html param
Parameters:
html_in new value of html param
Returns:
FALSE-no html in output, TRUE-output html text
int hocr::Hocr::get_font () [inline]
get font param
Returns:
font code of objct
int hocr::Hocr::set_font (const int font_in) [inline]
set font param
Parameters:
font_in new value of font param
Returns:
font code of objct
unsigned char hocr::Hocr::get_nikud () [inline]
get nikud param
Returns:
nikud of objct
unsigned char hocr::Hocr::set_nikud (const unsigned char nikud_in) [inline]
set nikud param
Parameters:
nikud_in new value of nikud param
Returns:
nikud of objct
int hocr::Hocr::get_paragraph_setup () [inline]
get paragraph setup param
Returns:
paragraph setup
int hocr::Hocr::set_paragraph_setup (const int paragraph_setup_in) [inline]
set paragraph setup param
Parameters:
paragraph_setup_in new value of font param
Returns:
paragraph setup of objct
const char* hocr::Hocr::get_build_string () [inline]
get build string
Returns:
build string
References hocr_get_build_string().
Field Documentation
int hocr::Hocr::progress
Referenced by do_font_recognition(), do_image_processing(), do_layout_analysis(), get_progress(), Hocr(), set_bitmap(), and set_pixbuf().
Author
Generated automatically by Doxygen for libhocr from the source code.