.TH "src/hocr.h" 3 "27 Jan 2008" "Version 0.10.5" "libhocr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hocr.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ho_pixbuf.h>\fP
.br
\fC#include <ho_bitmap.h>\fP
.br
\fC#include <ho_objmap.h>\fP
.br
\fC#include <ho_layout.h>\fP
.br
\fC#include <ho_dimentions.h>\fP
.br
\fC#include <ho_segment.h>\fP
.br
\fC#include <ho_font.h>\fP
.br
\fC#include <ho_recognize.h>\fP
.br
\fC#include <ho_string.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBHOCR_H\fP   1"
.br
.ti -1c
.RI "#define \fBBEGIN_C_DECLS\fP"
.br
.ti -1c
.RI "#define \fBEND_C_DECLS\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define HOCR_H   1"
.PP
.SS "#define BEGIN_C_DECLS"
.PP
.SS "#define END_C_DECLS"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for libhocr from the source code.
