.TH "src/hocrpp.h" 3 "23 May 2008" "Version 0.10.10" "libhocr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/hocrpp.h \- libhocr main C++ language header. 
.SH SYNOPSIS
.br
.PP
\fC#include <hocr.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBhocr\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBhocr::Hocr\fP"
.br
.RI "\fI\fBHocr\fP class. \fP"
.in -1c
.SH "Detailed Description"
.PP 
libhocr main C++ language header. 

libhocr - LIBrary for Hebrew Optical Character Recognition 
.SH "Author"
.PP 
Generated automatically by Doxygen for libhocr from the source code.
