.TH "ho_string" 3 "31 Jul 2008" "Version 0.10.17" "libhocr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ho_string \- libhocr string struct  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ho_string.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBstring\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBallocated_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
libhocr string struct 
.SH "Field Documentation"
.PP 
.SS "char* \fBho_string::string\fP"
.PP
Referenced by hocr::Hocr::get_text().
.SS "int \fBho_string::size\fP"
.PP
.SS "int \fBho_string::allocated_size\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libhocr from the source code.
